import Branding from "@/components/Branding";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Info from "@/components/Info";
import Stories from "@/components/Stories";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@900,700,500,300,400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex flex-col items-center min-h-screen">
        <Header />
        <Hero />
        <Info />
        <Branding />
        <Stories />
        <Footer />
      </main>
    </>
  );
}
